### ISSUE TITLE
Observers have been removed in Rails 4

### ISSUE THREAD

**Issue by jcoyne** [state-machines/state_machines-activemodel#24]
However this documentation still refers to `ActiveModel::Observer`: https://github.com/state-machines/state_machines-activemodel/blob/master/lib/state_machines/integrations/active_model.rb#L186-L238

**Comment by seuros** [comment]
It was extracted from Rails core .

You can have them here https://github.com/state-machines/state_machines-activemodel-observers

**Comment by jcoyne** [comment]
@seuros should the documentation mention that the example code requires an extra gem?

**Comment by jcoyne** [comment]
@seuros should the documentation mention that the example code requires an extra gem?

**Comment by seuros** [comment]
Yes . Can you open a PR  with the changes ?
