### ISSUE TITLE
Active Model compatibility

### ISSUE THREAD

**Issue by Mingan** [state-machines/state_machines-activemodel#3]
Hi, I'm trying to use this gem along with [state-machines_audit-trail](https://github.com/state-machines/state_machines-audit_trail). My only problem is that my application is running Rails 3 and therefore ActiveModel 3.2.21. 

I can see, that the support for 3.2 was dropped in version 0.0.3, but I'm unable to discern what was the reason. Is there some change in the ActiveModel API which required the change or you just didn't need it any more and decided to drop it? Tests for the current version pass when run against 3.2.21 so I'm hopeful that it was the latter.

**Comment by seuros** [comment]
The legacy gems worked for 3.2.
The support was dropped to allow the gems to move forward. The previous project was so massive that it became a big headache to maintain (support of all rubies, Rails from 2.3).

**Comment by Mingan** [comment]
Thank you for the quick reply. I'm not sure I understand what you mean. What legacy gem do you mean?

I tried using the last revision of this gem prior to 0.0.3 but it doesn't play well with others because the gem was renamed in between and `state_machines-audit_trail` requires `state_machines-activemodel` not `state_machines-activerecord`. So going back to the last version of the gem isn't an option. The only option left is forking the current version and loosening the dependency requirement. My question is whether there's some known API change which would make it a headache, or you don't know because you just dropped the support because it was too much of a burden and there's a chance that it might work.

**Comment by seuros** [comment]
sorry for late reply , this is the legacy gem : https://github.com/wvanbergen/state_machine-audit_trail

**Comment by Mingan** [comment]
Hardly a late reply! This is excellent. Thank you :+1:
