### ISSUE TITLE
Use absolute paths in tests

### ISSUE THREAD

**Issue by balasankarc** [state-machines/state_machines-activemodel#5]
Hi,
I am helping with the packaging of this gem in Debian. The test machine_with_internationalization_test.rb uses a relative path (in line 161) which will work only when used with bundler. The lib folder will not be available through that relative path in other methods, like OS packages.

Is there any way to access that file (/../lib/state_machines/integrations/active_model/locale.rb) without a relative path?

**Comment by rafaelfranca** [comment]
It is a absolute path in that line, see the `File.dirname(__FILE__)` there. https://github.com/state-machines/state_machines-activemodel/blob/48d73cb3a00048e7e29e41a8f1016f6781e3f069/test/machine_with_internationalization_test.rb#L161

It should not work only with bundler. I'm closing this issue. Let me know if it is solved or not.
